[package]
name = "rl-tut-rust"
version = "0.1.0"
authors = ["Dominic Torruellas <dtorruellas@gmail.com>"]

[dependencies]
tcod = { version = "*", features = ["serialization"] }
rand = "0.3.17"
serde = "*"
serde_derive = "*"
serde_json = "*"